version: '3.3'
services:
  neo4j-node: 
    image: neo4j:5-community
    container_name: neo4j-node
    restart: unless-stopped
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    environment: 
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_server.memory.heap.max_size=1G
    volumes:
      - neo4j_conf:/conf
      - neo4j_data:/data
      - neo4j_import:/import
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    networks:
      - adt-network
  cache:
    image: redis:6.2-alpine
    container_name: cache-1
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data
    networks:
      - adt-network
  mongo:
    image: mongo:5.0
    container_name: mongo-1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=adt
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - adt-network
  
  db:
    image: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    networks:
      - adt-network

  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_KRAFT_CLUSTER_ID: "dh6khitPSDGZSBOjNeTC_g"
    # healthcheck:
    #   test: ["CMD", "nc", "-vz", "localhost", "9092"]
    volumes:
      - kafka_volume:/bitnami/kafka
    networks:
      - adt-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8080:8080"
    # depends_on:
    #   kafka-node:
    #     condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka1:9092"
      KAFKA_CLUSTERS_0_NAME: "kraft"
    networks:
      - adt-network
volumes:
  neo4j_conf:
  neo4j_data:
  neo4j_import:
  neo4j_logs:
  neo4j_plugins:
  mongo-entrypoint:
  mongodb:
  mongoconfig:
  cache:
  db-volume:
  kafka_volume:

networks:
  adt-network:
    driver: "bridge"
    external: false